---
- name: Install glance
  apt: 
    name=glance
    state=present

- name: Install glance client
  apt: 
    name=python-glanceclient
    state=present

- name: Add glance database
  mysql_db: 
    name=glance
    state=present

- name: Add keystone database user
  mysql_user: 
    name=glance 
    password={{ glance_db_pass }} 
    priv=glance.*:ALL,GRANT 
    host='%' 
    state=present

- name: Create glance-api.conf
  template:
    src=glance-api.conf
    dest=/etc/glance/glance-api.conf
    owner=glance
    group=glance
    mode=0644

- name: Create glance-registry.conf
  template:
    src=glance-registry.conf
    dest=/etc/glance/glance-registry.conf
    owner=glance
    group=glance
    mode=0644

- name: Restart glance-api
  service:
    name=glance-api
    state=restarted

- name: Restart glance-registry
  service:
    name=glance-registry
    state=restarted

#Sync keystone db

- name: Sync keystone database
  command: su -s /bin/sh -c "glance-manage db_sync" glance

#Basic tenant and user creation

- name: Create glance user
  shell: OS_SERVICE_TOKEN={{ admin_token }} OS_SERVICE_ENDPOINT=http://127.0.0.1:35357/v2.0 /usr/bin/keystone \
           user-create --name glance --pass "{{ glance_pass }}" && touch /var/log/keystone/glance_user_create
    creates=/var/log/keystone/glance_user_create

- name: Assign admin role to glance user
  shell: OS_SERVICE_TOKEN={{ admin_token }} OS_SERVICE_ENDPOINT=http://127.0.0.1:35357/v2.0 /usr/bin/keystone \
           user-role-add --user glance --tenant service --role admin && touch /var/log/keystone/glance_role_assign
    creates=/var/log/keystone/glance_role_assign

- name: Create glance service
  shell: OS_SERVICE_TOKEN={{ admin_token }} OS_SERVICE_ENDPOINT=http://127.0.0.1:35357/v2.0 /usr/bin/keystone \
           service-create --name glance --type image --description "Glance"  && touch /var/log/keystone/glance_service_create
    creates=/var/log/keystone/glance_service_create

- name: Create glance endpoint
  shell: OS_SERVICE_TOKEN={{ admin_token }} OS_SERVICE_ENDPOINT=http://127.0.0.1:35357/v2.0 /usr/bin/keystone \
           endpoint-create \
           --service-id $(OS_SERVICE_TOKEN={{ admin_token }} OS_SERVICE_ENDPOINT=http://127.0.0.1:35357/v2.0 keystone service-list | awk '/ image / {print $2}') \
           --publicurl http://{{ public_ip }}:9292 \
           --internalurl http://{{ ansible_all_ipv4_addresses[0] }}:9292 \
           --adminurl http://{{ ansible_all_ipv4_addresses[0] }}:9292 \
           --region {{ region }} && touch /var/log/keystone/glance_endpoint_create
    creates=/var/log/keystone/glance_endpoint_create
