---
- name: Install neutron
  apt: 
    name={{ item }}
    state=present
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent

- name: Create neutron.conf
  template:
    src=neutron.conf
    dest=/etc/neutron/neutron.conf
    owner=neutron
    group=neutron
    mode=0644

- name: Create ml2_conf.ini
  template:
    src=ml2_conf.ini
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=neutron
    group=neutron
    mode=0644

- name: Create l3_agent.ini
  template:
    src=l3_agent.ini
    dest=/etc/neutron/l3_agent_conf.ini
    owner=neutron
    group=neutron
    mode=0644

- name: Create dhcp_agent.ini
  template:
    src=dhcp_agent.ini
    dest=/etc/neutron/dhcp_agent.ini
    owner=neutron
    group=neutron
    mode=0644

- name: Create metadata_agent.ini
  template:
    src=metadata_agent.ini
    dest=/etc/neutron/metadata_agent.ini
    owner=neutron
    group=neutron
    mode=0644

- name: Setup sysctl.conf
  lineinfile:
    dest=/etc/sysctl.conf
    line={{ item }}
  with_items:
    - "net.ipv4.ip_forward=1"
    - "net.ipv4.conf.all.rp_filter=0"
    - "net.ipv4.conf.default.rp_filter=0"

- name: Reload sysctl.conf
  command: sysctl -p

- name: Restart openvswitch
  service:
    name=openvswitch-switch
    state=restarted

- name: Create br-ex
  command: ovs-vsctl add-br br-ex
    creates=/sys/class/net/br-ex

- name: Get IP address
  shell: ip addr show dev eth0 | grep -Po 'inet \K[\d.]+/\d+' | xargs echo -n
  register: ip_and_cidr

- name: Switch bridge
  shell: nohup `ip addr del {{ ip_and_cidr.stdout_lines[0] }} dev eth0 && ovs-vsctl add-port br-ex eth0 && dhclient br-ex` &


- name: Restart neutron
  service:
    name={{ item }}
    state=restarted
  with_items:
    - neutron-server

